# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/TianQiLi/TQRepo.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'HQFQLDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HQFQLDemo
  pod 'HQFQLPaySDK'
  #pod 'HQFQLPaySDK' ,:path=> './../../'
end



 